In [2]:
import pandas as pd

In [33]:
df = pd.read_csv("DJ_adapted.csv", parse_dates=['Date'])
df.head()

        Date   OpenDJ   HighDJ    LowDJ   CloseDJ
0 1994-01-01  3756.60  3790.70  3715.24   3756.60
1 1994-01-02  3756.60  3790.70  3715.24   3756.60
2 1994-01-03  3756.60  3790.70  3715.24   3756.60
3 1994-01-04  3783.90  3798.25  3718.89   3783.90
4 1994-01-05  3798.82  3821.33  3750.41   3798.82

In [32]:
df = df.drop(['Vol.', '% var.'], axis=1)
df.columns = ['']
df.head()

KeyError: "['Vol.', '% var.'] not found in axis"

In [34]:
df.sort_values('Date', inplace=True)
date_range = pd.date_range(start=df['Date'].min(), end=df['Date'].max())
df.head()

        Date   OpenDJ   HighDJ    LowDJ   CloseDJ
0 1994-01-01  3756.60  3790.70  3715.24   3756.60
1 1994-01-02  3756.60  3790.70  3715.24   3756.60
2 1994-01-03  3756.60  3790.70  3715.24   3756.60
3 1994-01-04  3783.90  3798.25  3718.89   3783.90
4 1994-01-05  3798.82  3821.33  3750.41   3798.82

In [35]:
df = df.set_index('Date').reindex(date_range).rename_axis('Date').reset_index()
df.head()

        Date   OpenDJ   HighDJ    LowDJ   CloseDJ
0 1994-01-01  3756.60  3790.70  3715.24   3756.60
1 1994-01-02  3756.60  3790.70  3715.24   3756.60
2 1994-01-03  3756.60  3790.70  3715.24   3756.60
3 1994-01-04  3783.90  3798.25  3718.89   3783.90
4 1994-01-05  3798.82  3821.33  3750.41   3798.82

In [36]:
df.fillna(method='ffill', inplace=True)
df.head()

C:\Users\julga\AppData\Local\Temp\ipykernel_19444\2766238617.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

        Date   OpenDJ   HighDJ    LowDJ   CloseDJ
0 1994-01-01  3756.60  3790.70  3715.24   3756.60
1 1994-01-02  3756.60  3790.70  3715.24   3756.60
2 1994-01-03  3756.60  3790.70  3715.24   3756.60
3 1994-01-04  3783.90  3798.25  3718.89   3783.90
4 1994-01-05  3798.82  3821.33  3750.41   3798.82

In [26]:
df.to_csv('DOW_JONES.csv', index=False)