In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("finished/Debt_finished.csv")
df.head()

         Date  Total_debt  Debt_GDP_percentage  Debt_per_capita
0  1994-01-01    249508.0                58.68           6294.0
1  1994-01-01    249508.0                58.68           6294.0
2  1994-01-02    249508.0                58.68           6294.0
3  1994-01-02    249508.0                58.68           6294.0
4  1994-01-03    249508.0                58.68           6294.0

In [6]:
df = df.drop_duplicates(subset=['Date', 'Total_debt', 'Debt_GDP_percentage', 'Debt_per_capita'])
df.to_csv("Debt_finished.csv", index=False)

In [21]:
df = df.drop(['Vol.', '% var.'], axis=1)
df.head()

       Fecha  Último Apertura  Máximo  Mínimo
0 2023-12-29  1,1036   1,1061  1,1085  1,1034
1 2023-12-28  1,1059   1,1107  1,1141  1,1055
2 2023-12-27  1,1103   1,1043  1,1123  1,1028
3 2023-12-26  1,1042   1,1010  1,1046  1,1008
4 2023-12-25  1,1007   1,1017  1,1022  1,0993

In [22]:
df.columns = ['Date', 'EUR_Price', "EUR_Open", "EUR_High", "EUR_Low"]
df.head()

        Date EUR_Price EUR_Open EUR_High EUR_Low
0 2023-12-29    1,1036   1,1061   1,1085  1,1034
1 2023-12-28    1,1059   1,1107   1,1141  1,1055
2 2023-12-27    1,1103   1,1043   1,1123  1,1028
3 2023-12-26    1,1042   1,1010   1,1046  1,1008
4 2023-12-25    1,1007   1,1017   1,1022  1,0993

In [23]:
numeric_cols = ['EUR_Price', 'EUR_Open', 'EUR_High', 'EUR_Low']
for col in numeric_cols:
    # Remove periods (thousand separators)
    df[col] = df[col].str.replace('.', '')
    # Replace commas (decimal separators) with periods
    df[col] = df[col].str.replace(',', '.')
    # Convert to float
    df[col] = df[col].astype(float)

In [24]:
df['Date'] = pd.to_datetime(df['Date'])

In [25]:
df = df.sort_values(by='Date')
df.head()

          Date  EUR_Price  EUR_Open  EUR_High  EUR_Low
259 2023-01-02     1.0662    1.0702    1.0708   1.0650
258 2023-01-03     1.0546    1.0663    1.0684   1.0519
257 2023-01-04     1.0599    1.0552    1.0636   1.0540
256 2023-01-05     1.0520    1.0604    1.0632   1.0515
255 2023-01-06     1.0644    1.0522    1.0648   1.0483

In [48]:
df['Open'], df['High'], df['Low'], df['Close'] = df['High'], df['Low'], df['Close'], df['Open']

In [49]:
df.columns = ['Date', 'Open', 'High', 'Low', 'Close']

In [50]:
df['AdjClose'] = df['Close']

In [51]:
df['Date'] = pd.to_datetime(df['Date'], format='%d.%m.%Y')

In [19]:
df.to_csv("EUR-2023.csv", index=False)