In [35]:
import pandas as pd

In [36]:
df = pd.read_csv("IBEX-23_sorted.csv", parse_dates=['Date'])
df.head()

        Date    Open    High     Low   Close  AdjClose
0 2023-01-01  8229.1  8290.4  8221.7  8229.1    8229.1
1 2023-01-02  8297.9  8384.9  8283.7  8369.7    8369.7
2 2023-01-03  8366.9  8454.3  8327.4  8397.4    8397.4
3 2023-01-04  8443.1  8560.5  8442.1  8559.8    8559.8
4 2023-01-05  8530.2  8618.9  8527.7  8607.6    8607.6

In [37]:
df = df.drop(['Volume'], axis=1)
df.head()

KeyError: "['Volume'] not found in axis"

In [38]:
df.sort_values('Date', inplace=True)
date_range = pd.date_range(start=df['Date'].min(), end=df['Date'].max())
df.head()

        Date    Open    High     Low   Close  AdjClose
0 2023-01-01  8229.1  8290.4  8221.7  8229.1    8229.1
1 2023-01-02  8297.9  8384.9  8283.7  8369.7    8369.7
2 2023-01-03  8366.9  8454.3  8327.4  8397.4    8397.4
3 2023-01-04  8443.1  8560.5  8442.1  8559.8    8559.8
4 2023-01-05  8530.2  8618.9  8527.7  8607.6    8607.6

In [39]:
df = df.set_index('Date').reindex(date_range).rename_axis('Date').reset_index()
df.head()

        Date    Open    High     Low   Close  AdjClose
0 2023-01-01  8229.1  8290.4  8221.7  8229.1    8229.1
1 2023-01-02  8297.9  8384.9  8283.7  8369.7    8369.7
2 2023-01-03  8366.9  8454.3  8327.4  8397.4    8397.4
3 2023-01-04  8443.1  8560.5  8442.1  8559.8    8559.8
4 2023-01-05  8530.2  8618.9  8527.7  8607.6    8607.6

In [40]:
df.fillna(method='ffill', inplace=True)
df.head()

C:\Users\julga\AppData\Local\Temp\ipykernel_9708\2766238617.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

        Date    Open    High     Low   Close  AdjClose
0 2023-01-01  8229.1  8290.4  8221.7  8229.1    8229.1
1 2023-01-02  8297.9  8384.9  8283.7  8369.7    8369.7
2 2023-01-03  8366.9  8454.3  8327.4  8397.4    8397.4
3 2023-01-04  8443.1  8560.5  8442.1  8559.8    8559.8
4 2023-01-05  8530.2  8618.9  8527.7  8607.6    8607.6

In [34]:
df.to_csv('IBEX-2023_updated.csv', index=False)