In [55]:
import pandas as pd
import calendar

In [56]:
path = "deaths.csv"
df = pd.read_csv(path)
df.head()

   PERIODO   VALOR   TIPO DATO  NOTA
0     2022  464417  Definitivo   NaN
1     2021  450744  Definitivo   NaN
2     2020  493776  Definitivo   NaN
3     2019  418703  Definitivo   NaN
4     2018  427721  Definitivo   NaN

In [57]:
df = df.drop(['TIPO DATO', 'NOTA'], axis=1)
dfs = []
df.head()

   PERIODO   VALOR
0     2022  464417
1     2021  450744
2     2020  493776
3     2019  418703
4     2018  427721

In [59]:
for index, row in df.iterrows():
    year = int(row[0])
    valor = int(row[1])
    
    start_date = pd.to_datetime(f"{year}-01-01")
    end_date = pd.to_datetime(f"{year}-12-31")

    if calendar.isleap(year):
        valor = int(valor / 366)
    else:
        valor = int(valor / 365)
    
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "Deaths": valor
        }
    )
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = "Deaths_updated.csv"
new_df.to_csv(output_csv_path, index=False)

C:\Users\julga\AppData\Local\Temp\ipykernel_16348\3538974478.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  year = int(row[0])
C:\Users\julga\AppData\Local\Temp\ipykernel_16348\3538974478.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  valor = int(row[1])