In [1]:
import pandas as pd

In [14]:
file_path = 'DOW_JONES.csv'
df = pd.read_csv(file_path)
df.head()

         Date      Price       Open       High        Low     Vol. Change %
0  12/31/2021  36,338.30  36,385.85  36,484.94  36,303.97  218.21M   -0.16%
1  12/30/2021  36,398.08  36,522.48  36,679.44  36,372.13  207.64M   -0.25%
2  12/29/2021  36,488.63  36,421.14  36,571.55  36,396.19  214.40M    0.25%
3  12/28/2021  36,398.21  36,302.99  36,527.26  36,302.99  239.09M    0.26%
4  12/27/2021  36,302.38  35,954.48  36,306.61  35,954.48  250.26M    0.98%

In [15]:
df = df.drop(['Vol.', 'Change %'], axis=1)
df.head()

         Date      Price       Open       High        Low
0  12/31/2021  36,338.30  36,385.85  36,484.94  36,303.97
1  12/30/2021  36,398.08  36,522.48  36,679.44  36,372.13
2  12/29/2021  36,488.63  36,421.14  36,571.55  36,396.19
3  12/28/2021  36,398.21  36,302.99  36,527.26  36,302.99
4  12/27/2021  36,302.38  35,954.48  36,306.61  35,954.48

In [16]:
df.columns = ['Date', 'DJ_close', 'DJ_open', 'DJ_high', 'DJ_low']
df['Date'] = pd.to_datetime(df['Date'])
df.head()

        Date   DJ_close    DJ_open    DJ_high     DJ_low
0 2021-12-31  36,338.30  36,385.85  36,484.94  36,303.97
1 2021-12-30  36,398.08  36,522.48  36,679.44  36,372.13
2 2021-12-29  36,488.63  36,421.14  36,571.55  36,396.19
3 2021-12-28  36,398.21  36,302.99  36,527.26  36,302.99
4 2021-12-27  36,302.38  35,954.48  36,306.61  35,954.48

In [17]:
numeric_cols = ['DJ_close', 'DJ_open', 'DJ_high', 'DJ_low']
for col in numeric_cols:
    # Remove periods (thousand separators)
    df[col] = df[col].str.replace(',', '')
    # Replace commas (decimal separators) with periods
    #df[col] = df[col].str.replace('.', '.')
    # Convert to float
    df[col] = df[col].astype(float)
df.head()

        Date  DJ_close   DJ_open   DJ_high    DJ_low
0 2021-12-31  36338.30  36385.85  36484.94  36303.97
1 2021-12-30  36398.08  36522.48  36679.44  36372.13
2 2021-12-29  36488.63  36421.14  36571.55  36396.19
3 2021-12-28  36398.21  36302.99  36527.26  36302.99
4 2021-12-27  36302.38  35954.48  36306.61  35954.48

In [18]:
df = df[['Date', 'DJ_open', 'DJ_high', 'DJ_low', 'DJ_close']]
df.head()

        Date   DJ_open   DJ_high    DJ_low  DJ_close
0 2021-12-31  36385.85  36484.94  36303.97  36338.30
1 2021-12-30  36522.48  36679.44  36372.13  36398.08
2 2021-12-29  36421.14  36571.55  36396.19  36488.63
3 2021-12-28  36302.99  36527.26  36302.99  36398.21
4 2021-12-27  35954.48  36306.61  35954.48  36302.38

In [19]:
df = df.sort_values(by='Date')
df.head()

          Date   DJ_open   DJ_high    DJ_low  DJ_close
251 2021-01-04  30627.47  30674.28  29881.82  30223.89
250 2021-01-05  30204.25  30504.89  30141.78  30391.60
249 2021-01-06  30362.78  31022.65  30313.07  30829.40
248 2021-01-07  30901.18  31193.40  30897.86  31041.13
247 2021-01-08  31069.58  31140.67  30793.27  31097.97

In [ ]:
df.to_csv('DOW_JONES_2021.csv', index=False)