In [17]:
import pandas as pd
import calendar

In [37]:
xls_file_path = "datos.xlsx"
df = pd.read_excel(xls_file_path, header=None)
df.head(347)

             0          1        2        3
0          NaT        NaN      NaN      NaN
1   2023-10-01  1572131.0      NaN      NaN
2   2023-09-01  1577266.0  109.77%  32646 €
3   2023-08-01  1563284.0  110.87%  32347 €
4   2023-07-01  1557406.0  110.45%  32226 €
..         ...        ...      ...      ...
342 1995-05-01   262931.0   60.62%   6633 €
343 1995-04-01   259881.0   59.91%   6556 €
344 1995-03-01   261636.0   60.32%   6600 €
345 1995-02-01   259119.0   60.96%   6537 €
346 1995-01-01   252452.0   59.39%   6369 €

[347 rows x 4 columns]

In [38]:
df = df.drop(0, axis=0)
df = df.drop(1, axis=0)

In [39]:
dfs = []
df = pd.DataFrame(df)

# Elimina el % y el € de las columnas que contienen estos caracteres
df[2] = df[2].str.rstrip('%')
df[3] = df[3].str.rstrip('€')

df.head(347)

             0          1       2       3
2   2023-09-01  1577266.0  109.77  32646
3   2023-08-01  1563284.0  110.87  32347
4   2023-07-01  1557406.0  110.45  32226
5   2023-06-01  1568743.0  111.25  32460
6   2023-05-01  1541752.0  111.62  32088
..         ...        ...     ...     ...
342 1995-05-01   262931.0   60.62   6633
343 1995-04-01   259881.0   59.91   6556
344 1995-03-01   261636.0   60.32   6600
345 1995-02-01   259119.0   60.96   6537
346 1995-01-01   252452.0   59.39   6369

[345 rows x 4 columns]

In [43]:
for index, row in df.iterrows():
    monthYear = row[0]
    debt = row[1]
    percentage = row[2]
    debt_per_capita = row[3]
    year = monthYear.year
    month = monthYear.month

    is_leap_year = calendar.isleap(year)
    
    start_date = pd.to_datetime(f"{year}-{month}-01")

    if month == 4 or month == 6 or month == 9 or month == 11:
        end_date = pd.to_datetime(f'{year}-{month}-30')
    elif month == 2:
        if is_leap_year:
            end_date = pd.to_datetime(f'{year}-{month}-29')
        else:
            end_date = pd.to_datetime(f'{year}-{month}-28')
    else:
        end_date = pd.to_datetime(f'{year}-{month}-31')
    
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "Debt": debt,
            "Percentage": percentage,
            "Debt_per_capita": debt_per_capita
        }
    )
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = "Debt_daily.csv"
new_df.to_csv(output_csv_path)