In [57]:
import pandas as pd
import calendar

In [58]:
xls_file_path = "datos.xlsx"
df = pd.read_excel(xls_file_path, header=None)
df.head()

         0   1    2           3
0  2023M12 NaN  0.0      Avance
1  2023M11 NaN -0.3  Definitivo
2  2023M10 NaN  0.3  Definitivo
3  2023M09 NaN  0.2  Definitivo
4  2023M08 NaN  0.5  Definitivo

In [59]:
df = df.drop(1, axis=1)
df = df.drop(3, axis=1)

In [60]:
dfs = []
df.head()

         0    2
0  2023M12  0.0
1  2023M11 -0.3
2  2023M10  0.3
3  2023M09  0.2
4  2023M08  0.5

In [61]:
for index, row in df.iterrows():
    monthYear = row[0]
    IPC = row[2]
    year = int(monthYear[0:4])
    month = int(monthYear[5:])

    is_leap_year = calendar.isleap(year)
    
    start_date = pd.to_datetime(f"{year}-{month}-01")

    if month == 4 or month == 6 or month == 9 or month == 11:
        end_date = pd.to_datetime(f'{year}-{month}-30')
    elif month == 2:
        if is_leap_year:
            end_date = pd.to_datetime(f'{year}-{month}-29')
        else:
            end_date = pd.to_datetime(f'{year}-{month}-28')
    else:
        end_date = pd.to_datetime(f'{year}-{month}-31')
    
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "IPC": IPC,
        }
    )
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = "Inflation_Rate_daily.csv"
new_df.to_csv(output_csv_path)