In [1]:
import pandas as pd

In [10]:
excel_file_path = 'datos.xlsx'
df = pd.read_excel(excel_file_path)
df.head()

     PERIOD  Unnamed: 1   VALUE
0  2023QIII         NaN  0.3023
1   2023QII         NaN  0.4365
2    2023QI         NaN  0.5722
3   2022QIV         NaN  0.4913
4  2022QIII         NaN  0.5305

In [11]:
df = df.drop(['Unnamed: 1'], axis=1)
dfs = []
df.head()

     PERIOD   VALUE
0  2023QIII  0.3023
1   2023QII  0.4365
2    2023QI  0.5722
3   2022QIV  0.4913
4  2022QIII  0.5305

In [21]:
for index, row in df.iterrows():
    trimester = row["PERIOD"]
    valor = row["VALUE"]

    # Extract year and trimester number
    year = int(trimester[0:4])
    trimester_num = {'I': 1, 'II': 2, 'III': 3, 'IV': 4}.get(trimester[5:])
    # Calculate the start date of the trimester
    start_date = pd.to_datetime(f"{year}-{(trimester_num - 1) * 3 + 1:02d}-01")

    # Calculate the end date of the trimester
    if trimester_num == 3 or trimester_num == 2:
        end_date = pd.to_datetime(f'{year}-{trimester_num * 3:02d}-30')
    else:
        end_date = pd.to_datetime(f'{year}-{trimester_num * 3:02d}-31')

    # Generate date range for the trimester
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    # Create a DataFrame with the date range and corresponding value
    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "Value": valor
        }
    )

    # Append the temporary DataFrame to the new DataFrame
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = 'GDP_daily.csv'
new_df.to_csv(output_csv_path, index=False)