In [3]:
import pandas as pd
import calendar

In [4]:
file_path = 'debt1.csv'
df = pd.read_csv(file_path)
dfs = []
df.head()

   Date  Total_debt  Debt_GDP_percentage  Debt_per_capita
0  2023   1554194.0               110.85          32205.5

In [22]:
df['Debt_GDP_percentage'] = df['Debt_GDP_percentage'] * 100
df.head()

   Date  TotalDebt  Debt_GDP_percentage Debt_per_capita
0  2022    1502804                111.6        31.277 €
1  2021    1428133                116.8        30.074 €
2  2020    1345786                120.3        28.393 €
3  2019    1223355                 98.2        25.846 €
4  2018    1208861                100.4        25.755 €

In [23]:
df['Debt_per_capita'] = df['Debt_per_capita'].str.replace('€', '').astype(float)
df['Debt_per_capita'] = df['Debt_per_capita'] * 1000
df.head()

   Date  TotalDebt  Debt_GDP_percentage  Debt_per_capita
0  2022    1502804                111.6          31277.0
1  2021    1428133                116.8          30074.0
2  2020    1345786                120.3          28393.0
3  2019    1223355                 98.2          25846.0
4  2018    1208861                100.4          25755.0

In [6]:
for index, row in df.iterrows():
    year = int(row[0])
    TotalDebt = row[1]
    Debt_percentage = row[2]
    per_capita = row[3]
    
    start_date = pd.to_datetime(f"{year}-01-01")
    end_date = pd.to_datetime(f"{year}-12-31")
    
    date_range = pd.date_range(start=start_date, end=end_date, freq="D")

    temp_df = pd.DataFrame(
        {
            "Date": date_range,
            "Total_debt": TotalDebt,
            "Debt_GDP_percentage": Debt_percentage,
            "Debt_per_capita": per_capita
        }
    )
    dfs.append(temp_df)
new_df = pd.concat(dfs, ignore_index=True)
new_df.drop_duplicates()
output_csv_path = "Debt.csv"
new_df.to_csv(output_csv_path,index=False)

C:\Users\julga\AppData\Local\Temp\ipykernel_22356\3502124624.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  year = int(row[0])
C:\Users\julga\AppData\Local\Temp\ipykernel_22356\3502124624.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  TotalDebt = row[1]
C:\Users\julga\AppData\Local\Temp\ipykernel_22356\3502124624.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Debt_percentage = row[2]
C:\Users\julga\AppData\Local\Temp\ipykernel_22356\3502124624.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  per_capita = row[3]